# To configure this application, create the file
#   XDG_CONFIG/doc-browser/config.yaml
# which usually is
#   /home/<your user name>/.config/doc-browser/config.yaml
# and then edit the interested configurations there, you don't
# have to copy all keys to that file, just copy the keys you
# are interested in is sufficient.


# NOTE:
# Currently, unless otherwise stated, all configuration
# changes require a restart of this application to take
# effect. Sorry for the trouble :(


# Zoom factor for QtWebEngine.
# ============================================================
# If the font is too big or too small in the tab, tweak this:
# - if you don't have HiDPI, try 1
# - otherwise, try 1.5, 2, or other values
WebEngineZoomFactor: 1.5


# Widths of the left column.
# ============================================================
# Width when displaying results from DevDocs and Dash
LeftColumnWidth: 430
# Width when displaying results from Hoogle
LeftColumnWidthHoogle: 700


# Serve the documentation using this port.
# ============================================================
# Restart all instances of this application after changing.
Port: 7701

# Whether the Window should capture focus on remote summons.
# ============================================================
# If set, the doc-browser-window will be raised and receive
# keyboard forcus. Otherwise, the window will be merely alerted.
# This might be desireable if you usually have the window
# opened on a second output and usually find what you are
# searching for in the first match
FocusOnSummon: True

# Directory that contains the MathJax distribution.
# ============================================================
# Hoogle documentation relies on MathJax to display, this
# option specifies where to look for such a distribution.
#
# This directory is used for offline displaying, so even if
# you specified the wrong directory, the Hoogle documentation
# will still work - as long as you have a internet connection.
#
# The directory contents should look something like this:
#
# $ ls /usr/share/mathjax/
# bower.json       extensions  localization
# composer.json    fonts       MathJax.js
# config           jax         package.json
# CONTRIBUTING.md  latest.js   README.md
#
# This directory should be absolute.
MathJaxDirectory: "/usr/share/mathjax"


# Customizable commands.
# ============================================================
# The "py" part in the query "/pyos.path" is called a command,
# you can use it to specify which docset you want to search.
#
# It has the same format as DefaultCommands, see there for
# the documentation and examples.
#
# Commands defined here will override those in
# DefaultCommands.
Commands: {}


# Do not change this, use Commands instead.
# ============================================================
# Commands are represented with YAML map, in this syntax:
#
#   <command string> : <command>
#        ↓                ↓
# e.g.  py : ["LimitToDevDocs", "Python", "3"]
#
# <command string> must be two characters long, and cannot
# contain '/'.
#
# These <command>s are available:
#
# - ["LimitToDevDocs", "<collection>", "<version prefix>"]
#   This command limit the search scope to the docsets that
#   satisfies these conditions:
#
#   - it is provided by DevDocs
#   - its collection is <collection>
#   - <version prefix> is a case-insensitive prefix of the
#     docset's version
#
#   You can use `doc-browser --list-installed-devdocs` to
#   query installed collection and versions.
#
# - ["LimitToDash", "<collection>", "<version prefix>"]
#   Similar to "LimitToDevDocs", but this command search
#   docsets provided by Dash.
#
#   You can use `doc-browser --list-installed-dash` to
#   query installed collection and versions.
#
# - ["HoogleLatest"]
#   Search with Hoogle, use the "latest" database, where
#   "latest" is defined to be the last of:
#
#   sort_with_dictionary_order_ascending(all_collections)
#
# - ["HoogleLimit", "<collection>"]
#   Search with Hoogle, use the database specified by
#   <collection>.
DefaultCommands:
  go: ["LimitToDevDocs", "Go", ""]
  hs: ["LimitToDevDocs", "Haskell", ""]
  mp: ["LimitToDevDocs", "Matplotlib", ""]
  np: ["LimitToDevDocs", "NumPy", ""]
  pd: ["LimitToDevDocs", "pandas", ""]
  py: ["LimitToDevDocs", "Python", "3"]
  p2: ["LimitToDevDocs", "Python", "2"]
  tf: ["LimitToDevDocs", "TensorFlow", ""]
  pg: ["LimitToDevDocs", "PostgreSQL", ""]
  sl: ["LimitToDevDocs", "SQLite", ""]
  er: ["LimitToDash", "Erlang", ""]
  sp: ["LimitToDash", "SciPy", ""]
  th: ["LimitToDash", "PyTorch", ""]
  rs: ["LimitToDash", "Rust", ""]
  hh: ["HoogleLatest"]


# Font for input area.
InputFont:
  Family: "Monospace"
  PointSize: 12

# Font for the "main" part of the search result.
MatchFontMain:
  Family: "Monospace"
  PointSize: 10

# Like MatchFontMain, but for Hoogle.
MatchFontMainHoogle:
  Family: "Monospace"
  PointSize: 10

# Font for package, module, and database version.
# Only used by Hoogle.
MatchFontMeta:
  Family: "Monospace"
  PointSize: 8

# Font for the docset version in the RHS of the match area.
# Not used by Hoogle
MatchFontVersion:
  Family: "SansSerif"
  PointSize: 6

# Font for the shortcut on the LHS of the match area.
MatchFontShortcut:
  Family: "Monospace"
  PointSize: 8

MatchBgColorNormal:   "#fdf6e3"
MatchBgColorSelected: "#586e75"

MatchFgColorNormal:   "#657b83"
MatchFgColorSelected: "#fdf6e3"

MatchFgColorLight: "#747f83"

# Border color for the input area.
InputBorderColor: "#586e75"

# vim: cc=62
